name: 'Validate PowerOn'
description: 'Validate PowerOn files against Symitar environments'
author: 'Libum, LLC'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  symitar-hostname:
    description: 'Symitar hostname (e.g., symitar.example.com)'
    required: true

  sym-number:
    description: 'Sym number to validate against'
    required: true

  symitar-user-number:
    description: 'Symitar user number for authentication'
    required: true

  symitar-user-password:
    description: 'Symitar user password for authentication'
    required: true

  ssh-username:
    description: 'SSH username for SSH connections (required for SSH connection type)'
    required: true

  ssh-password:
    description: 'SSH password for SSH connections (required for SSH connection type)'
    required: true

  ssh-port:
    description: 'SSH port for SSH connections (default: 22)'
    required: false
    default: '22'

  api-key:
    description: 'API key for Symitar connections'
    required: true

  connection-type:
    description: 'Connection type: "https" or "ssh" (default: ssh)'
    required: false
    default: 'ssh'

  poweron-directory:
    description: 'Directory containing PowerOn files (default: REPWRITERSPECS/)'
    required: false
    default: 'REPWRITERSPECS/'

  target-branch:
    description: 'Target branch to compare against for changed files (e.g., origin/main)'
    required: false

  validate-ignore:
    description: 'Comma-separated list of PowerOn filenames to ignore during validation'
    required: false
    default: ''

outputs:
  files-validated:
    description: 'Number of PowerOn files validated'

  files-passed:
    description: 'Number of PowerOn files that passed validation'

  files-failed:
    description: 'Number of PowerOn files that failed validation'

  duration:
    description: 'Validation duration in seconds'

runs:
  using: node20
  main: dist/index.js
